### ISSUE TITLE
Live Candlestick

### ISSUE THREAD

**Issue by firmai** [peter-pri/lm-usage#1]
Hi nice project, can you post a gif or video of what the live candle stick looks like. Cheers, Derek

**Comment by peter-pri** [comment]
Hi Derek, the Images are now visible in the Readme File. Cheers, Peter

Derek Snow ***@***.***> schrieb am Do., 23. Sep. 2021, 14:19:

**Comment by peter-pri** [comment]
The live Mode Looks the same, only the refresh time is shorter.

Peter Information ***@***.***> schrieb am Mi., 29. Sep. 2021,
11:35:
